import {
  SellerStore,
  SellerOrder,
  SellerProduct,
  SellerEarningsSummary,
  SellerLedgerEntry,
  SellerNotification,
  SellerAnalyticsMetrics,
} from '../types/seller';

export const INITIAL_STORES: SellerStore[] = [
  {
    id: 'sel-01',
    name: 'Sri Lakshmi Hardware & Electrical Mart',
    ownerName: 'Suresh Babu',
    hubType: 'Authorised Switchgear & Fasteners Hub',
    categories: ['Electrical & Lighting', 'Hardware & Fasteners', 'Power Tools & Equipment', 'Safety & PPE'],
    phone: '+91 98450 12345',
    email: 'suresh.mart@qcom-sellers.in',
    address: '14th Main Rd, 4th Block, Koramangala, Bengaluru, Karnataka 560034',
    locality: 'Koramangala 4th Block',
    areaName: 'Koramangala, Bengaluru',
    city: 'Bengaluru',
    pincode: '560034',
    coordinates: { lat: 12.9352, lng: 77.6245 },
    accessibleEntranceCoords: { lat: 12.9354, lng: 77.6248 },
    pickupNotes: 'Loading bay via back gate on 14th Main. Ring dispatch bell #2.',
    gstin: '29ABCDE1234F1Z5',
    panNumber: 'ABCDE1234F',
    bankAccount: {
      accountNumber: '918020045582910',
      ifsc: 'HDFC0000053',
      bankName: 'HDFC Bank, Koramangala Branch',
      accountHolderName: 'Sri Lakshmi Hardware & Electricals LLP',
    },
    status: 'ACTIVE',
    isStoreOnline: true,
    canReceiveOrders: true,
    isOrderingEnabled: true,
    isPaused: false,
    commissionRatePercent: 12.0,
    rating: 4.88,
    reviewsCount: 1420,
    basePrepMins: 2.5,
    slaAdherencePercent: 98.6,
    joinedDate: '2025-11-10',
    documents: {
      gstVerified: true,
      panVerified: true,
      bankVerified: true,
      tradeLicenseVerified: true,
      tradeLicenseNumber: 'BBMP/TR/2024/KA-8821',
    },
    operatingHours: {
      openTime: '07:30',
      closeTime: '21:30',
      daysOpen: 'Mon - Sun',
    },
  },
  {
    id: 'sel-02',
    name: 'Astral & Finolex Pipes Wholesale Depot',
    ownerName: 'M. Venkat Reddy',
    hubType: 'CPVC, UPVC & Sanitaryware Depot',
    categories: ['Plumbing & Sanitaryware', 'Adhesives & Chemicals', 'Hardware & Fasteners'],
    phone: '+91 98450 23456',
    email: 'venkat.pipes@qcom-sellers.in',
    address: 'Plot 42, Hosur Main Road, Near Silk Board, HSR Sector 2, Bengaluru 560068',
    locality: 'HSR Layout Sector 2',
    areaName: 'HSR Layout, Bengaluru',
    city: 'Bengaluru',
    pincode: '560068',
    coordinates: { lat: 12.9121, lng: 77.6446 },
    accessibleEntranceCoords: { lat: 12.9123, lng: 77.6449 },
    pickupNotes: 'Pipe racks are adjacent to shutter 3. Heavy vehicles use side lane.',
    gstin: '29BCDEF2345G1Z6',
    panNumber: 'BCDEF2345G',
    bankAccount: {
      accountNumber: '0029104000184920',
      ifsc: 'ICIC0000029',
      bankName: 'ICICI Bank, Silk Board Branch',
      accountHolderName: 'Bengaluru Pipe Depot Pvt Ltd',
    },
    status: 'ACTIVE',
    isStoreOnline: true,
    canReceiveOrders: true,
    isOrderingEnabled: true,
    isPaused: false,
    commissionRatePercent: 12.5,
    rating: 4.92,
    reviewsCount: 2180,
    basePrepMins: 3.0,
    slaAdherencePercent: 99.1,
    joinedDate: '2025-08-14',
    documents: {
      gstVerified: true,
      panVerified: true,
      bankVerified: true,
      tradeLicenseVerified: true,
      tradeLicenseNumber: 'BBMP/TR/2023/KA-4419',
    },
    operatingHours: {
      openTime: '08:00',
      closeTime: '21:00',
      daysOpen: 'Mon - Sat',
    },
  },
];

export const INITIAL_SELLER_PRODUCTS: SellerProduct[] = [
  {
    id: 'prod-01',
    sku: 'PLM-VAL-01',
    name: 'Supreme 1/2" Brass Quarter-Turn Angle Valve',
    category: 'Plumbing & Sanitaryware',
    subcategory: 'Valves & Taps',
    brand: 'SupremeFit',
    price: 185,
    mrp: 240,
    unit: 'Piece',
    stockCount: 38,
    minStockAlert: 15,
    inStock: true,
    status: 'IN_STOCK',
    binLocation: 'Aisle P1 • Bay 04',
    description: 'Heavy quarter-turn ceramic disc brass angle valve for geysers, faucets, washbasins, and flush tanks. 100% leak-tested.',
    specs: {
      'Size': '1/2" BSP (15mm)',
      'Material': 'Forged Brass Chrome Plated',
      'Pressure Rating': '16 Bar',
      'Warranty': '7 Years Manufacturer Warranty',
    },
    hsnCode: '8481.80.30',
    gstRatePercent: 18,
    rating: 4.9,
    reviewsCount: 312,
    imageUrl: 'https://images.unsplash.com/photo-1585338107529-13afc5f02586?w=400&auto=format&fit=crop&q=80',
    badge: 'High Velocity',
    tags: ['angle valve', 'plumbing', 'brass', 'geyser tap'],
    updatedAt: '2026-09-17T18:30:00Z',
  },
  {
    id: 'prod-02',
    sku: 'PLM-TEF-03',
    name: 'SealLock High-Density Teflon PTFE Tape (Pack of 3)',
    category: 'Plumbing & Sanitaryware',
    subcategory: 'Sealants & Gaskets',
    brand: 'SealLock Pro',
    price: 45,
    mrp: 60,
    unit: 'Pack of 3',
    stockCount: 8,
    minStockAlert: 20,
    inStock: true,
    status: 'LOW_STOCK',
    binLocation: 'Aisle P1 • Bay 01',
    description: 'Industrial plumber Teflon thread sealing tape. Resists high water pressure and hot geyser lines. Guaranteed leak-free joints.',
    specs: {
      'Dimensions': '12mm x 10m x 0.1mm',
      'Material': '100% Pure Virgin PTFE',
      'Standard': 'ISI Grade A Thread Sealer',
    },
    hsnCode: '3920.99.10',
    gstRatePercent: 18,
    rating: 4.9,
    reviewsCount: 520,
    imageUrl: 'https://images.unsplash.com/photo-1616401784845-180882ba9ba8?w=400&auto=format&fit=crop&q=80',
    badge: 'Fast Seller',
    tags: ['teflon', 'ptfe', 'plumbing tape'],
    updatedAt: '2026-09-17T19:10:00Z',
  },
  {
    id: 'prod-03',
    sku: 'PLM-HOS-06',
    name: 'HydroFlex SS 304 Braided Geyser Connection Hose (18" / 450mm)',
    category: 'Plumbing & Sanitaryware',
    subcategory: 'Sanitary Fixtures',
    brand: 'HydroFlex',
    price: 135,
    mrp: 180,
    unit: 'Piece',
    stockCount: 0,
    minStockAlert: 10,
    inStock: false,
    status: 'OUT_OF_STOCK',
    binLocation: 'Aisle P2 • Bay 02',
    description: 'Heavy duty SS 304 braided stainless steel hose with solid brass hex nuts and pre-inserted rubber washers.',
    specs: {
      'Length': '18 Inch (450mm)',
      'Fitting': '1/2" Female BSP',
      'Core': 'EPDM Non-toxic inner tube',
    },
    hsnCode: '8307.10.00',
    gstRatePercent: 18,
    rating: 4.8,
    reviewsCount: 198,
    imageUrl: 'https://images.unsplash.com/photo-1542013936693-884638332954?w=400&auto=format&fit=crop&q=80',
    tags: ['geyser hose', 'ss 304', 'water pipe'],
    updatedAt: '2026-09-17T14:20:00Z',
  },
  {
    id: 'prod-04',
    sku: 'ELE-MCB-16',
    name: 'Havells 16A Single Pole C-Curve MCB (10kA Breaking Capacity)',
    category: 'Electrical & Lighting',
    subcategory: 'Switchgear & Breakers',
    brand: 'Havells Euro-X',
    price: 165,
    mrp: 225,
    unit: 'Piece',
    stockCount: 44,
    minStockAlert: 12,
    inStock: true,
    status: 'IN_STOCK',
    binLocation: 'Aisle E1 • Shelf 03',
    description: 'High-speed tripping miniature circuit breaker with silver alloy contacts and bi-metallic thermal overload protection.',
    specs: {
      'Current Rating': '16 Amp',
      'Breaking Capacity': '10kA @ 240V AC',
      'Standard': 'IS/IEC 60898-1',
    },
    hsnCode: '8536.20.30',
    gstRatePercent: 18,
    rating: 4.95,
    reviewsCount: 420,
    imageUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=400&auto=format&fit=crop&q=80',
    badge: 'Pro Tier 1',
    tags: ['mcb', 'havells', 'breaker', 'switchgear'],
    updatedAt: '2026-09-17T17:45:00Z',
  },
  {
    id: 'prod-05',
    sku: 'ELE-WAG-413',
    name: 'Wago 221-413 3-Conductor Lever Wire Connectors (Box of 50)',
    category: 'Electrical & Lighting',
    subcategory: 'Wire Connectors & Lugs',
    brand: 'Wago Germany',
    price: 385,
    mrp: 490,
    unit: 'Box of 50',
    stockCount: 19,
    minStockAlert: 8,
    inStock: true,
    status: 'IN_STOCK',
    binLocation: 'Aisle E2 • Bin 11',
    description: 'Original German tool-free transparent lever nuts for solid, stranded, and fine-stranded copper wires up to 4mm².',
    specs: {
      'Conductor Range': '0.2 to 4 mm²',
      'Rated Current': '32 Amp',
      'Rated Voltage': '450V AC',
    },
    hsnCode: '8536.90.90',
    gstRatePercent: 18,
    rating: 4.98,
    reviewsCount: 680,
    imageUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=400&auto=format&fit=crop&q=80',
    badge: 'Electrician Favorite',
    tags: ['wago', 'connectors', 'lever nuts', 'splice'],
    updatedAt: '2026-09-17T16:00:00Z',
  },
  {
    id: 'prod-06',
    sku: 'ELE-TAP-ANC',
    name: 'Anchor by Panasonic Heavy PVC Insulation Tape (Pack of 5)',
    category: 'Electrical & Lighting',
    subcategory: 'Insulation & Tapes',
    brand: 'Anchor Panasonic',
    price: 65,
    mrp: 90,
    unit: 'Pack of 5',
    stockCount: 62,
    minStockAlert: 20,
    inStock: true,
    status: 'IN_STOCK',
    binLocation: 'Aisle E1 • Bin 02',
    description: 'Flame-retardant ISI marked black electrical tape. High elongation and moisture resistance.',
    specs: {
      'Width': '18mm x 7.5m length',
      'Dielectric Strength': '40 kV/mm',
      'Grade': 'ISI 7809',
    },
    hsnCode: '3919.10.00',
    gstRatePercent: 18,
    rating: 4.85,
    reviewsCount: 890,
    imageUrl: 'https://images.unsplash.com/photo-1572981779307-38b8cabb2407?w=400&auto=format&fit=crop&q=80',
    tags: ['insulation tape', 'anchor', 'electrical'],
    updatedAt: '2026-09-17T15:20:00Z',
  },
  {
    id: 'prod-07',
    sku: 'TLS-BSC-DISC',
    name: 'Bosch Expert 4" (105mm) Ultra-Thin Stainless Steel Cutting Disc',
    category: 'Power Tools & Equipment',
    subcategory: 'Cutting & Grinding Discs',
    brand: 'Bosch Professional',
    price: 38,
    mrp: 55,
    unit: 'Piece',
    stockCount: 95,
    minStockAlert: 25,
    inStock: true,
    status: 'IN_STOCK',
    binLocation: 'Aisle T1 • Rack 02',
    description: '1.0mm ultra-thin inox cut-off wheel for fast, burr-free cuts in SS pipes, MS angles, and channel bars.',
    specs: {
      'Bore Size': '16mm (Standard 4" grinder)',
      'Max RPM': '15,300 RPM (80 m/s)',
      'Material': 'Aluminum Oxide with fiberglass grid',
    },
    hsnCode: '6804.22.90',
    gstRatePercent: 18,
    rating: 4.92,
    reviewsCount: 1140,
    imageUrl: 'https://images.unsplash.com/photo-1504148455328-c376907d081c?w=400&auto=format&fit=crop&q=80',
    badge: 'Jobsite Must-Have',
    tags: ['cutting disc', 'bosch', 'angle grinder'],
    updatedAt: '2026-09-17T18:10:00Z',
  },
  {
    id: 'prod-08',
    sku: 'FAS-UNB-M08',
    name: 'Unbrako Grade 8.8 Galvanized M8 x 40mm Hex Bolts (Pack of 20)',
    category: 'Hardware & Fasteners',
    subcategory: 'Bolts & Machine Screws',
    brand: 'Unbrako Fasteners',
    price: 110,
    mrp: 145,
    unit: 'Pack of 20',
    stockCount: 6,
    minStockAlert: 15,
    inStock: true,
    status: 'LOW_STOCK',
    binLocation: 'Aisle F2 • Bin 14',
    description: 'High tensile metric hex head cap screws electro-galvanized for corrosion resistance.',
    specs: {
      'Thread Pitch': '1.25mm Standard Coarse',
      'Tensile Strength': '800 N/mm²',
      'Standard': 'DIN 933 / ISO 4017',
    },
    hsnCode: '7318.15.00',
    gstRatePercent: 18,
    rating: 4.88,
    reviewsCount: 240,
    imageUrl: 'https://images.unsplash.com/photo-1586864387967-d02ef85d93e8?w=400&auto=format&fit=crop&q=80',
    tags: ['bolts', 'm8', 'unbrako', 'fasteners'],
    updatedAt: '2026-09-17T17:00:00Z',
  },
  {
    id: 'prod-09',
    sku: 'SFT-KRM-HLM',
    name: 'Karam ISI Heavy Duty Ratchet Safety Helmet (Yellow)',
    category: 'Safety & PPE',
    subcategory: 'Head & Eye Protection',
    brand: 'Karam Safety',
    price: 180,
    mrp: 260,
    unit: 'Piece',
    stockCount: 22,
    minStockAlert: 10,
    inStock: true,
    status: 'IN_STOCK',
    binLocation: 'Aisle S1 • Shelf 01',
    description: 'UV stabilized high density polymer safety helmet with 6-point textile suspension and wheel ratchet adjuster.',
    specs: {
      'Standard': 'IS 2925:1984 Certified',
      'Electrical Insulation': 'Up to 2,000V',
      'Sweatband': 'Cushioned Anti-Allergic',
    },
    hsnCode: '6506.10.90',
    gstRatePercent: 18,
    rating: 4.9,
    reviewsCount: 310,
    imageUrl: 'https://images.unsplash.com/photo-1508873696983-2df5293cb32b?w=400&auto=format&fit=crop&q=80',
    badge: 'ISI Certified',
    tags: ['safety helmet', 'karam', 'ppe', 'head gear'],
    updatedAt: '2026-09-17T13:45:00Z',
  },
  {
    id: 'prod-10',
    sku: 'ADH-FEV-1KG',
    name: 'Fevicol ProBond High-Strength Waterproof Wood Adhesive (1kg)',
    category: 'Adhesives & Chemicals',
    subcategory: 'Wood Glues & Pastes',
    brand: 'Pidilite Fevicol',
    price: 245,
    mrp: 295,
    unit: '1 kg Jar',
    stockCount: 0,
    minStockAlert: 8,
    inStock: false,
    status: 'OUT_OF_STOCK',
    binLocation: 'Aisle A1 • Shelf 02',
    description: 'Specially engineered for bonding PVC and acrylic sheets to plywood, MDF and wood joints. Fast setting in 2 hours.',
    specs: {
      'Setting Time': '2 Hours Fast Handling',
      'Water Resistance': 'EN 204 D3 Compliant',
      'Coverage': 'Approx 40-50 sq.ft per kg',
    },
    hsnCode: '3506.91.90',
    gstRatePercent: 18,
    rating: 4.94,
    reviewsCount: 540,
    imageUrl: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?w=400&auto=format&fit=crop&q=80',
    tags: ['fevicol', 'wood adhesive', 'carpentry', 'pidilite'],
    updatedAt: '2026-09-17T11:20:00Z',
  },
];

export const INITIAL_ORDERS: SellerOrder[] = [
  {
    id: 'ORD-2026-921402',
    orderNumber: 'Q-921402',
    status: 'placed',
    placedAt: new Date(Date.now() - 3 * 60 * 1000).toISOString(), // 3 mins ago
    estimatedDeliveryAt: new Date(Date.now() + 11 * 60 * 1000).toISOString(),
    subtotal: 415,
    tax: 74.7,
    deliveryFee: 0,
    handlingFee: 15,
    total: 504.7,
    sellerEarnings: 365.2, // subtotal minus 12% commission
    commissionAmount: 49.8,
    commissionRatePercent: 12.0,
    tdsAmount: 4.15,
    items: [
      {
        productId: 'prod-01',
        productName: 'Supreme 1/2" Brass Quarter-Turn Angle Valve',
        brand: 'SupremeFit',
        category: 'Plumbing & Sanitaryware',
        unit: 'Piece',
        price: 185,
        mrp: 240,
        quantity: 2,
        binLocation: 'Aisle P1 • Bay 04',
        image: 'https://images.unsplash.com/photo-1585338107529-13afc5f02586?w=200&auto=format&fit=crop&q=80',
        isPacked: false,
        hsnCode: '8481.80.30',
        gstRatePercent: 18,
      },
      {
        productId: 'prod-02',
        productName: 'SealLock High-Density Teflon PTFE Tape (Pack of 3)',
        brand: 'SealLock Pro',
        category: 'Plumbing & Sanitaryware',
        unit: 'Pack of 3',
        price: 45,
        mrp: 60,
        quantity: 1,
        binLocation: 'Aisle P1 • Bay 01',
        image: 'https://images.unsplash.com/photo-1616401784845-180882ba9ba8?w=200&auto=format&fit=crop&q=80',
        isPacked: false,
        hsnCode: '3920.99.10',
        gstRatePercent: 18,
      },
    ],
    customer: {
      id: 'cust-8812',
      name: 'Rajesh M.',
      phone: '+91 98XXX-XX891',
      maskedPhone: '+91 98XXX-XX891 (Masked via QCOM IVR)',
      isMasked: true,
      virtualProxyNumber: '080-4890-7711',
      accountType: 'plumber',
      businessName: 'Mistri Plumbing Works',
      gstin: '29AABCP8812M1ZN',
    },
    jobSite: {
      address: 'Koramangala 4th Block (Zone 2, Dispatch Area)',
      deliveryLocality: 'Koramangala 4th Block',
      landmark: 'Near BDA Complex',
      floorUnit: 'Dispatch to Courier Hub Bay',
      siteContactName: 'Rajesh M.',
      sitePhone: '+91 98XXX-XX891',
      tradeType: 'Plumber',
      coordinates: { lat: 12.9365, lng: 77.6255 },
    },
    rider: {
      id: 'rider-01',
      name: 'Anil Kumar',
      phone: '+91 98450 99812',
      vehicle: 'Bajaj Chetak EV (#KA-01-EV-4210)',
      rating: 4.95,
      etaMinutes: 4,
      distanceMeters: 650,
      photo: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
    },
    deliveryOtp: '4921',
    paymentMethod: 'Instant UPI',
    paymentStatus: 'PAID',
    clientInvoiceNeeded: true,
    notes: ['Customer requires urgent delivery to avoid site water cutoff.'],
  },
  {
    id: 'ORD-2026-884129',
    orderNumber: 'Q-884129',
    status: 'picking',
    placedAt: new Date(Date.now() - 7 * 60 * 1000).toISOString(), // 7 mins ago
    estimatedDeliveryAt: new Date(Date.now() + 8 * 60 * 1000).toISOString(),
    preparationStartTime: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    subtotal: 780,
    tax: 140.4,
    deliveryFee: 0,
    handlingFee: 15,
    total: 935.4,
    sellerEarnings: 686.4,
    commissionAmount: 93.6,
    commissionRatePercent: 12.0,
    tdsAmount: 7.8,
    items: [
      {
        productId: 'prod-04',
        productName: 'Havells 16A Single Pole C-Curve MCB (10kA Breaking Capacity)',
        brand: 'Havells Euro-X',
        category: 'Electrical & Lighting',
        unit: 'Piece',
        price: 165,
        mrp: 225,
        quantity: 2,
        binLocation: 'Aisle E1 • Shelf 03',
        image: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=200&auto=format&fit=crop&q=80',
        isPacked: true,
        hsnCode: '8536.20.30',
        gstRatePercent: 18,
      },
      {
        productId: 'prod-05',
        productName: 'Wago 221-413 3-Conductor Lever Wire Connectors (Box of 50)',
        brand: 'Wago Germany',
        category: 'Electrical & Lighting',
        unit: 'Box of 50',
        price: 385,
        mrp: 490,
        quantity: 1,
        binLocation: 'Aisle E2 • Bin 11',
        image: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=200&auto=format&fit=crop&q=80',
        isPacked: true,
        hsnCode: '8536.90.90',
        gstRatePercent: 18,
      },
      {
        productId: 'prod-06',
        productName: 'Anchor by Panasonic Heavy PVC Insulation Tape (Pack of 5)',
        brand: 'Anchor Panasonic',
        category: 'Electrical & Lighting',
        unit: 'Pack of 5',
        price: 65,
        mrp: 90,
        quantity: 1,
        binLocation: 'Aisle E1 • Bin 02',
        image: 'https://images.unsplash.com/photo-1572981779307-38b8cabb2407?w=200&auto=format&fit=crop&q=80',
        isPacked: false,
        hsnCode: '3919.10.00',
        gstRatePercent: 18,
      },
    ],
    customer: {
      id: 'cust-4419',
      name: 'Santosh K.',
      phone: '+91 98XXX-XX910',
      maskedPhone: '+91 98XXX-XX910 (Masked via QCOM IVR)',
      isMasked: true,
      virtualProxyNumber: '080-4890-7712',
      accountType: 'electrician',
      businessName: 'Santosh Power Systems',
      gstin: '29BCDFG5510Q1Z8',
    },
    jobSite: {
      address: '100ft Road Corridor, Koramangala 1st Block (Zone 1)',
      deliveryLocality: 'Koramangala 1st Block',
      landmark: 'Opposite Cult Fitness',
      floorUnit: 'Ground Floor Commercial Bay',
      gateCode: 'Direct access',
      siteContactName: 'Santosh K.',
      sitePhone: '+91 98XXX-XX910',
      tradeType: 'Electrician',
      coordinates: { lat: 12.9340, lng: 77.6290 },
    },
    rider: {
      id: 'rider-03',
      name: 'Deepak Sharma',
      phone: '+91 99881 77312',
      vehicle: 'TVS iQube Electric (#KA-01-IQ-0814)',
      rating: 4.88,
      etaMinutes: 2,
      distanceMeters: 380,
      photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80',
    },
    deliveryOtp: '8204',
    paymentMethod: 'Trade Credit (Net 30)',
    paymentStatus: 'PAID',
    clientInvoiceNeeded: true,
  },
  {
    id: 'ORD-2026-773105',
    orderNumber: 'Q-773105',
    status: 'packed',
    placedAt: new Date(Date.now() - 14 * 60 * 1000).toISOString(),
    estimatedDeliveryAt: new Date(Date.now() + 5 * 60 * 1000).toISOString(),
    preparationStartTime: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
    packedTime: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    subtotal: 256,
    tax: 46.08,
    deliveryFee: 0,
    handlingFee: 15,
    total: 317.08,
    sellerEarnings: 225.28,
    commissionAmount: 30.72,
    commissionRatePercent: 12.0,
    tdsAmount: 2.56,
    items: [
      {
        productId: 'prod-07',
        productName: 'Bosch Expert 4" (105mm) Ultra-Thin Stainless Steel Cutting Disc',
        brand: 'Bosch Professional',
        category: 'Power Tools & Equipment',
        unit: 'Piece',
        price: 38,
        mrp: 55,
        quantity: 2,
        binLocation: 'Aisle T1 • Rack 02',
        image: 'https://images.unsplash.com/photo-1504148455328-c376907d081c?w=200&auto=format&fit=crop&q=80',
        isPacked: true,
        hsnCode: '6804.22.90',
        gstRatePercent: 18,
      },
      {
        productId: 'prod-09',
        productName: 'Karam ISI Heavy Duty Ratchet Safety Helmet (Yellow)',
        brand: 'Karam Safety',
        category: 'Safety & PPE',
        unit: 'Piece',
        price: 180,
        mrp: 260,
        quantity: 1,
        binLocation: 'Aisle S1 • Shelf 01',
        image: 'https://images.unsplash.com/photo-1508873696983-2df5293cb32b?w=200&auto=format&fit=crop&q=80',
        isPacked: true,
        hsnCode: '6506.10.90',
        gstRatePercent: 18,
      },
    ],
    customer: {
      name: 'Praveen G.',
      phone: '+91 97XXX-XX820',
      maskedPhone: '+91 97XXX-XX820 (Masked via QCOM IVR)',
      isMasked: true,
      virtualProxyNumber: '080-4890-7713',
      accountType: 'contractor',
      businessName: 'Gowda Civil Infra',
      gstin: '29ABCDE7741P1ZQ',
    },
    jobSite: {
      address: 'Industrial Layout, Koramangala 5th Block (Zone 3)',
      deliveryLocality: 'Koramangala 5th Block',
      landmark: 'Behind Depot Bay',
      floorUnit: 'Fabrication Shed 2',
      siteContactName: 'Praveen G.',
      sitePhone: '+91 97XXX-XX820',
      tradeType: 'Fabricator',
      coordinates: { lat: 12.9312, lng: 77.6210 },
    },
    rider: {
      id: 'rider-02',
      name: 'Rajesh Varma',
      phone: '+91 98201 44520',
      vehicle: 'Ather 450X Pro (#KA-05-AT-1904)',
      rating: 4.91,
      etaMinutes: 1,
      distanceMeters: 180,
      photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80',
    },
    deliveryOtp: '7192',
    paymentMethod: 'Corporate Card',
    paymentStatus: 'PAID',
    clientInvoiceNeeded: true,
  },
  {
    id: 'ORD-2026-664190',
    orderNumber: 'Q-664190',
    status: 'out_for_delivery',
    placedAt: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    estimatedDeliveryAt: new Date(Date.now() + 3 * 60 * 1000).toISOString(),
    preparationStartTime: new Date(Date.now() - 22 * 60 * 1000).toISOString(),
    packedTime: new Date(Date.now() - 17 * 60 * 1000).toISOString(),
    subtotal: 555,
    tax: 99.9,
    deliveryFee: 0,
    handlingFee: 15,
    total: 669.9,
    sellerEarnings: 488.4,
    commissionAmount: 66.6,
    commissionRatePercent: 12.0,
    tdsAmount: 5.55,
    items: [
      {
        productId: 'prod-01',
        productName: 'Supreme 1/2" Brass Quarter-Turn Angle Valve',
        brand: 'SupremeFit',
        category: 'Plumbing & Sanitaryware',
        unit: 'Piece',
        price: 185,
        mrp: 240,
        quantity: 3,
        binLocation: 'Aisle P1 • Bay 04',
        image: 'https://images.unsplash.com/photo-1585338107529-13afc5f02586?w=200&auto=format&fit=crop&q=80',
        isPacked: true,
        hsnCode: '8481.80.30',
        gstRatePercent: 18,
      },
    ],
    customer: {
      name: 'Vikas R.',
      phone: '+91 99XXX-XX412',
      maskedPhone: '+91 99XXX-XX412 (Masked via QCOM IVR)',
      isMasked: true,
      virtualProxyNumber: '080-4890-7714',
      accountType: 'plumber',
    },
    jobSite: {
      address: 'Outer Ring Road Sector (Zone 5)',
      deliveryLocality: 'Outer Ring Road',
      floorUnit: 'Villa 12',
      siteContactName: 'Vikas R.',
      sitePhone: '+91 99XXX-XX412',
      tradeType: 'Plumber',
      coordinates: { lat: 12.9280, lng: 77.6320 },
    },
    rider: {
      id: 'rider-04',
      name: 'Manoj Gowda',
      phone: '+91 97410 88231',
      vehicle: 'Ola S1 Pro (#KA-51-OL-6512)',
      rating: 4.93,
      etaMinutes: 3,
      distanceMeters: 750,
      photo: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=120&auto=format&fit=crop&q=80',
    },
    deliveryOtp: '3318',
    paymentMethod: 'Instant UPI',
    paymentStatus: 'PAID',
    clientInvoiceNeeded: false,
  },
  {
    id: 'ORD-2026-553108',
    orderNumber: 'Q-553108',
    status: 'delivered',
    placedAt: new Date(Date.now() - 95 * 60 * 1000).toISOString(),
    estimatedDeliveryAt: new Date(Date.now() - 82 * 60 * 1000).toISOString(),
    deliveredAt: new Date(Date.now() - 80 * 60 * 1000).toISOString(),
    subtotal: 1100,
    tax: 198,
    deliveryFee: 0,
    handlingFee: 15,
    total: 1313,
    sellerEarnings: 968,
    commissionAmount: 132,
    commissionRatePercent: 12.0,
    tdsAmount: 11.0,
    items: [
      {
        productId: 'prod-08',
        productName: 'Unbrako Grade 8.8 Galvanized M8 x 40mm Hex Bolts (Pack of 20)',
        brand: 'Unbrako Fasteners',
        category: 'Hardware & Fasteners',
        unit: 'Pack of 20',
        price: 110,
        mrp: 145,
        quantity: 10,
        binLocation: 'Aisle F2 • Bin 14',
        image: 'https://images.unsplash.com/photo-1586864387967-d02ef85d93e8?w=200&auto=format&fit=crop&q=80',
        isPacked: true,
        hsnCode: '7318.15.00',
        gstRatePercent: 18,
      },
    ],
    customer: {
      name: 'Ramesh N.',
      phone: '+91 98XXX-XX200',
      maskedPhone: '+91 98XXX-XX200 (Masked via QCOM IVR)',
      isMasked: true,
      virtualProxyNumber: '080-4890-7715',
      accountType: 'contractor',
      businessName: 'Naidu PEB Structures',
      gstin: '29AABCN9845R1ZK',
    },
    jobSite: {
      address: 'Phase 2 Sector, Electronic City (Zone 8)',
      deliveryLocality: 'Electronic City Phase 2',
      siteContactName: 'Ramesh N.',
      sitePhone: '+91 98XXX-XX200',
      tradeType: 'Fabricator',
      coordinates: { lat: 12.8420, lng: 77.6790 },
    },
    deliveryOtp: '6019',
    paymentMethod: 'Instant UPI',
    paymentStatus: 'PAID',
    clientInvoiceNeeded: true,
  },
];

export const INITIAL_EARNINGS: SellerEarningsSummary = {
  todaySales: 3106,
  todayOrders: 5,
  todayNetEarnings: 2733.28,
  averageOrderValue: 621.2,
  growthVsYesterdayPercent: 14.8,
  pendingPayableBalance: 18450.5,
  settledBalance: 84200.0,
  totalLifetimeSales: 486250.0,
  totalLifetimeEarnings: 427900.0,
  monthSales: 64200.0,
  tdsDeducted: 4862.5,
  commissionPaid: 7704.0,
  nextPayoutDate: 'Tomorrow at 10:00 AM (Daily Automated NEFT)',
  totalCommissionDeducted: 58350.0,
  totalTdsDeducted: 4862.5,
  pendingPayoutCount: 14,
};

export const INITIAL_LEDGER: SellerLedgerEntry[] = [
  {
    id: 'led-101',
    date: 'Today',
    timestamp: '14:15 PM',
    type: 'PRODUCT_SALE',
    category: 'CREDIT',
    title: 'Order Delivered #Q-553108',
    description: '10x Unbrako M8 Fasteners - Gross Sale ₹1,100 (Net credit after 12% commission & 1% TDS)',
    amount: 957.0,
    orderNumber: 'Q-553108',
    status: 'CLEARED',
  },
  {
    id: 'led-102',
    date: 'Today',
    timestamp: '11:40 AM',
    type: 'PAYOUT_SETTLED',
    category: 'DEBIT',
    title: 'Daily Auto-Payout Released (HDFC Bank)',
    description: 'NEFT to A/C ending 2910 • UTR #HDFC00941829410',
    amount: 24680.0,
    status: 'CLEARED',
    utrNumber: 'HDFC00941829410',
    payoutMode: 'NEFT',
  },
  {
    id: 'led-103',
    date: 'Yesterday',
    timestamp: '21:05 PM',
    type: 'PRODUCT_SALE',
    category: 'CREDIT',
    title: 'Order Delivered #Q-551982',
    description: '4x Havells Euro-X MCBs + 2x Wago Connectors',
    amount: 1258.4,
    orderNumber: 'Q-551982',
    status: 'CLEARED',
  },
  {
    id: 'led-104',
    date: 'Yesterday',
    timestamp: '17:22 PM',
    type: 'REFUND_ADJUSTMENT',
    category: 'DEBIT',
    title: 'Customer Cancellation Reversal',
    description: 'Order #Q-550912 cancelled prior to dispatch - stock auto-restocked',
    amount: 185.0,
    orderNumber: 'Q-550912',
    status: 'CLEARED',
  },
  {
    id: 'led-105',
    date: '15 Sep 2026',
    timestamp: '11:30 AM',
    type: 'PAYOUT_SETTLED',
    category: 'DEBIT',
    title: 'Daily Auto-Payout Released (HDFC Bank)',
    description: 'NEFT to A/C ending 2910 • UTR #HDFC00941781290',
    amount: 31400.0,
    status: 'CLEARED',
    utrNumber: 'HDFC00941781290',
    payoutMode: 'NEFT',
  },
];

export const INITIAL_NOTIFICATIONS: SellerNotification[] = [
  {
    id: 'notif-01',
    type: 'NEW_ORDER',
    title: 'New Order #Q-921402 Needs Acceptance',
    message: '2 items (Supreme Valve + Teflon Tape) · ₹504.70 · Rider Anil Kumar ETA 4 mins',
    context: 'Customer at Prestige Greenwoods requested urgent dispatch.',
    timestamp: '3 mins ago',
    isRead: false,
    priority: 'URGENT',
    actionLabel: 'Accept & Pick',
    actionTab: 'orders',
    referenceId: 'ORD-2026-921402',
  },
  {
    id: 'notif-02',
    type: 'LOW_STOCK',
    title: 'SealLock Teflon Tape Running Low',
    message: 'Only 8 units remaining in bin Aisle P1 • Bay 01 (Min threshold: 20 units)',
    context: 'High velocity item with multiple orders today.',
    timestamp: '45 mins ago',
    isRead: false,
    priority: 'HIGH',
    actionLabel: 'Update Stock',
    actionTab: 'inventory',
    referenceId: 'prod-02',
  },
  {
    id: 'notif-03',
    type: 'OUT_OF_STOCK',
    title: 'HydroFlex Geyser Hose Out of Stock',
    message: 'Stock count reached 0. Product automatically hidden from customer search.',
    context: 'Restock immediately to resume incoming orders.',
    timestamp: '2 hours ago',
    isRead: true,
    priority: 'HIGH',
    actionLabel: 'Restock',
    actionTab: 'inventory',
    referenceId: 'prod-03',
  },
  {
    id: 'notif-04',
    type: 'PAYOUT_RELEASED',
    title: 'Daily Payout of ₹24,680 Processed',
    message: 'Transferred via NEFT to HDFC Bank A/C ending 2910 (UTR: HDFC00941829410)',
    context: 'Settlement for sales up to 16 Sep 2026.',
    timestamp: '5 hours ago',
    isRead: true,
    priority: 'NORMAL',
    actionLabel: 'View Ledger',
    actionTab: 'earnings',
  },
];

export const INITIAL_ANALYTICS: SellerAnalyticsMetrics = {
  hourlyOrderDistribution: [
    { hour: '08:00', count: 3, sales: 1420 },
    { hour: '09:00', count: 7, sales: 3890 },
    { hour: '10:00', count: 12, sales: 6420 },
    { hour: '11:00', count: 10, sales: 5100 },
    { hour: '12:00', count: 8, sales: 4200 },
    { hour: '13:00', count: 4, sales: 1980 },
    { hour: '14:00', count: 6, sales: 3410 },
    { hour: '15:00', count: 9, sales: 4850 },
    { hour: '16:00', count: 11, sales: 6100 },
    { hour: '17:00', count: 8, sales: 4400 },
  ],
  categoryPerformance: [
    { category: 'Plumbing & Sanitaryware', sharePercent: 42, sales: 17997 },
    { category: 'Electrical & Lighting', sharePercent: 34, sales: 14569 },
    { category: 'Hardware & Fasteners', sharePercent: 15, sales: 6427 },
    { category: 'Power Tools & Safety', sharePercent: 9, sales: 3857 },
  ],
  fulfillmentSla: {
    avgPrepTimeMins: 2.1,
    targetPrepTimeMins: 3.0,
    onTimeFulfillmentPercent: 98.6,
    handoverTimeAvgMins: 1.4,
  },
  slaAdherencePercent: 98.4,
  avgPreparationMinutes: 4.2,
  cancellationRatePercent: 0.4,
  hourlyVolume: [
    { hour: '9 AM', orders: 2, sales: 940 },
    { hour: '10 AM', orders: 4, sales: 2480 },
    { hour: '11 AM', orders: 5, sales: 3120 },
    { hour: '12 PM', orders: 3, sales: 1850 },
    { hour: '2 PM', orders: 3, sales: 1720 },
    { hour: '4 PM', orders: 4, sales: 2890 },
    { hour: '6 PM', orders: 2, sales: 1100 },
  ],
  topProducts: [
    {
      id: 'prod-07',
      name: 'Bosch Expert 4" Cutting Disc',
      unitsSold: 34,
      revenue: 1292,
      stockRemaining: 95,
    },
    {
      id: 'prod-01',
      name: 'Supreme 1/2" Brass Angle Valve',
      unitsSold: 28,
      revenue: 5180,
      stockRemaining: 38,
    },
    {
      id: 'prod-04',
      name: 'Havells 16A Single Pole MCB',
      unitsSold: 22,
      revenue: 3630,
      stockRemaining: 44,
    },
    {
      id: 'prod-05',
      name: 'Wago 221-413 Wire Connectors',
      unitsSold: 14,
      revenue: 5390,
      stockRemaining: 19,
    },
  ],
};
